name: LLVM release build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "centos:7" 
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          yum update -y
          yum install -y git perl-IPC-Cmd perl-Test-Simple xz-devel xz-libs wget git gcc gcc-c++ autoconf automake libtool make pkgconfig which flex bison python3 python3-pip
          pip3 install meson ninja pyelftools
          export PIP_ONLY_BINARY=cmake
          pip3 install meson ninja pyelftools cmake
          unset PIP_ONLY_BINARY
          
          gcc --version
          g++ --version
          cmake --version
          
          yum install -y centos-release-scl
          yum install -y devtoolset-11
          scl enable devtoolset-11 bash
          
      - name: check dependencies
        run: |
          gcc --version
          g++ --version
          cmake --version
          
      - name: build llvm
        run: |
          wget -c https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/llvm-project-17.0.6.src.tar.xz
          tar xf llvm-project-17.0.6.src.tar.xz
          cd llvm-project-17.0.6.src && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/llvm -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -G "Unix Makefiles" ../llvm
          make -j


